### ISSUE TITLE
Packaging to pypi

### ISSUE THREAD

**Issue by peniqliotuv** [puddly/pytest-unraisable#1]
@puddly I came across your repo here https://github.com/pytest-dev/pytest-asyncio/issues/184 after getting into a deep rabbit hole about how to fail tests if coroutines were not awaited. Would it be possible to package this into pypi?

**Comment by puddly** [comment]
It looks like pytest implemented this functionality a few months after I made this repo. This unit test fails for me, as expected:

```Python
import pytest

async def async_coro():
    await asyncio.sleep(0)

@pytest.mark.filterwarnings("error::pytest.PytestUnraisableExceptionWarning")
@pytest.mark.filterwarnings("error::RuntimeWarning")
@pytest.mark.asyncio
async def test_coroutine_not_awaited():
    async_coro()
```

**Comment by peniqliotuv** [comment]
Confirmed this works, thank you @puddly !
